// Termini damanhuriani — fonte: "Glossario lista termini damanhuriani italiano-inglese" (PDF).
// [italiano, english, nota italiana (opzionale), nota english (opzionale)]
const GLOSSARY = [
  ["Adonajba","Adonajba","Lingua sacra per “chakra”, anche se un AdonajBa è più complesso del solo chakra.","Sacred language for chakra, even though an AdonajBa is more complex than just the chakra."],
  ["Albero del Saluto","Salutation Tree"],
  ["Saluto all'Albero","Tree salutation"],
  ["Alchimia","Alchemy"],
  ["Aldilà","The Beyond"],
  ["Ambasciatore","Ambassador"],
  ["Aria, Acqua, Terra, Fuoco, Etere","Air, Water, Earth, Fire, Ether","Intesi come elementi alchemici.","Understood as alchemical elements."],
  ["Armonizzazione Interiore","Inner Harmonizing"],
  ["Atlantide","Atlantis"],
  ["Baita","Baita Temple"],
  ["bambini liberati","liberated children"],
  ["Bastone rituale","Ritual staff"],
  ["Biblioteca astrale","Astral library"],
  ["Blaitz","Blaitz (flash operation)","Operazione lampo.","Flash operation."],
  ["Borgomastro","Mayor"],
  ["Boschetto della coscienza","Grove of Consciousness"],
  ["Bosco Sacro","Sacred Woods"],
  ["Cabina selfica","Selfic Cabin"],
  ["Calice","Chalice"],
  ["Camera Alta","High Chamber"],
  ["Capitano","Captain"],
  ["Caponucleo","Nucleo representative"],
  ["Casa Ragazzi","Casa Ragazzi","La casa in cui vivono alcuni adolescenti damanhuriani.","The house where some Damanhurian teenagers live."],
  ["Cavalieri, cavalierato","Knights, knighthood"],
  ["Cerchio rituale","Ritual circle"],
  ["Circuiti (labirinti di pietre)","Circuits (stone labyrinths)"],
  ["Cittadella dell'Iniziato","Citadel of the Initiate"],
  ["Cittadinanza","Citizenship"],
  ["Cittadino, cittadini","Citizen, citizens"],
  ["Civiltà antica","Ancient civilization"],
  ["Cogenitori","Co-parents"],
  ["Collegio di Giustizia","College of Justice"],
  ["Commemorazione dei defunti","Commemoration of the Dead"],
  ["Comune Antitransgenico","GMO-free municipality"],
  ["Conte di Cagliostro","Count Cagliostro"],
  ["Consiglio (membri del)","Council (members of the council)"],
  ["Contatto con quadri selfici","Contact with Selfic Paintings"],
  ["Corpo del Tecnarcato","Tecnarcato"],
  ["Corpo di Meditazione","School of Meditation"],
  ["Corpo Sociale","Social Body"],
  ["Costituzione","Constitution"],
  ["Credito, Crediti","Credito, Creditos"],
  ["Culla (Tempio Bosco Sacro)","Cradle"],
  ["Damanhuriani","Damanhurians"],
  ["Danza Sacra","Sacred Dance"],
  ["Dio interiore","Inner god, Inner divinity"],
  ["Divinazione, mantica","Divination"],
  ["Doppio","Double"],
  ["Ecosistema spirituale","Spiritual ecosystem"],
  ["Epagomenoi","Epagomenal days"],
  ["Equinozio","Equinox"],
  ["Esoterismo","Esotericism"],
  ["Età dell'Acquario","Age of Aquarius"],
  ["Falco Tarassaco","Falco Tarassaco","Il fondatore di Damanhur.","Founder of Damanhur."],
  ["Festa della Primavera","Spring Festival"],
  ["Festa della Terrazzatura","Festival of Terrazzatura","Festa del lavoro devozionale.","A festival of devotional work."],
  ["Filatoio Cosmico","Cosmic spinning wheel"],
  ["Fisica spirituale","Spiritual Physics"],
  ["Fissazione","Fissazione","Pratica spirituale di fissazione.","A spiritual practice of fixation."],
  ["Fonocromoterapia","Sound and color therapy"],
  ["Forze dell'Oracolo","Forces of the Oracle"],
  ["Forze della Natura","Forces of Nature"],
  ["Forze divine","Divine forces"],
  ["Gioco della Vita","Game of Life"],
  ["Governatore","Governor"],
  ["Graal","Grail"],
  ["Gradi della Scuola di Meditazione","Grades of the School of Meditation"],
  ["Grado esoterico","Esoteric grade"],
  ["Guaritore spirituale","Spiritual Healer"],
  ["Guerra d'Arte","Battle of the arts"],
  ["Guida spirituale","Spiritual guide","Così si descrive Falco Tarassaco.","Used to describe Falco Tarassaco."],
  ["Horusiadi","Horusiadi","I giochi estivi damanhuriani.","The Damanhurian summer games."],
  ["Illuminato, Illuminazione","Enlightened being, Enlightenment"],
  ["Individuo comunità","Individual as community","Concetto per cui tutte le parti interiori di una persona sono allineate, come in una comunità funzionante.","The concept that all inner parts of an individual are aligned, as in a functional community."],
  ["Iniziato, Iniziazione","Initiate, Initiation"],
  ["Inviato","Envoy"],
  ["Karma","Karma"],
  ["Koan","Koan","Storia, dialogo o domanda usata nelle pratiche spirituali per mettere alla prova il percorso di chi studia.","A story, dialogue, question or statement used in spiritual practices to provoke and test a student's progress."],
  ["Labirinto (Il)","The Labyrinth"],
  ["Legge dei Quarti","Law of the Quarters"],
  ["Legge del karma","Law of karma"],
  ["Legge Sincronicità","Law of Synchronicity"],
  ["Leggere il fuoco","Fire scrying"],
  ["Leggere l'acqua","Water scrying"],
  ["Libero arbitrio","Free will"],
  ["Linee bianche e blu del Tempio Aperto","White and blue lines of the Open Temple"],
  ["Linee Sincroniche","Synchronic Lines"],
  ["Linee telluriche","Telluric lines"],
  ["Lingua Sacra","Sacred Language"],
  ["Magia","Magic"],
  ["Mandala","Mandala"],
  ["Mantica dell'agnello","Divination of the Lamb"],
  ["Matrimonio esoterico","Esoteric marriage"],
  ["Matrice di Popolo","Matrix of the Popolo","Come nel “Popolo spirituale”.","As in Spiritual Popolo."],
  ["Meditazione","Meditation","Abbreviazione di Scuola di Meditazione.","Short for School of Meditation."],
  ["Medianità","Mediumship"],
  ["Medicina integrata","Integrative medicine"],
  ["Menhir","Menhir, standing stones"],
  ["Metratura","Metratura","La meditazione in movimento.","Meditation in movement."],
  ["Mezzi","Mezzi","Pratica damanhuriana specifica che crea veicoli astrali, o merkaba.","A specific Damanhurian practice that creates astral vehicles, or merkaba."],
  ["Microlinee","Microlines"],
  ["Midnight Action","Midnight Action"],
  ["Miniera temporale","Time mine"],
  ["Missione","Mission"],
  ["Mito dello Specchio","Myth of the (Broken) Mirror"],
  ["Mondo dell'Oltre","The Beyond"],
  ["Mondo della Fiamma","World of the Flame"],
  ["Mondo delle Idee","World of ideas"],
  ["Mondo delle Spirali","World of spirals"],
  ["Mondo Madre","Mother world"],
  ["Monacato, monaco / monaca","Monasticism, monk / nun"],
  ["Musica delle piante","Plant music"],
  ["Musica rituale, musica damanhuriana","Ritual music, Damanhurian music"],
  ["New Life","New Life"],
  ["Nome segreto","Secret name"],
  ["Nucleo","Nucleo","Struttura familiare di base di Damanhur: un gruppo di persone che vivono in uno spazio comune condividendo un progetto.","The base family structure of Damanhur: a group of people living in a common space and sharing a specific project."],
  ["Nucleo comunità","Nucleo community"],
  ["Offerta di fine mese","End of the month offering"],
  ["Olio Caldo","Olio Caldo","Progetto damanhuriano di autosufficienza.","A Damanhurian self-sufficiency project."],
  ["Oltre (L')","The Beyond"],
  ["Oracolo","Oracle"],
  ["Parlamento dei Popoli","Parliament of Peoples"],
  ["Parola di potenza","Word of power"],
  ["Percorrere spirali e labirinti","Walking spirals and labyrinths"],
  ["Percorso spirituale","Spiritual path"],
  ["Perla (La)","The Pearl"],
  ["Pizia","Priestess, called Pythies"],
  ["Popolo","People"],
  ["Popolo spirituale","Spiritual People"],
  ["Pranoselfica","Pranoselfica"],
  ["Pranoterapia","Pranatherapy"],
  ["Pregnazione","Infusion","Da intendere come “infondere” (mai impregnazione, che significa mettere incinta).","To infuse (never “impregnation”, which means to make pregnant)."],
  ["Prova di coraggio","Test of courage"],
  ["Psicometria","Psychometrics"],
  ["Purificazione del cibo, degli oggetti","Blessing of food, objects"],
  ["Quadri Selfici","Selfic Paintings"],
  ["Rinascimento damanhuriano","Damanhurian Renaissance"],
  ["Rinascita dell'umanità","Rebirth of humanity"],
  ["Risveglio dei Sensi Interni","Reawakening of the Inner Senses"],
  ["Rito","Rite","Si riferisce a una cerimonia particolare, la cui messa in atto costituisce un rituale.","Refers to a particular ceremony, whose detailed enactment constitutes a ritual."],
  ["Rito del Solstizio, dell'Equinozio","Ritual of the Solstice, Equinox"],
  ["Rito della Cornucopia","Ritual of the Cornucopia (Horn of Plenty)"],
  ["Rito della Forma","Ritual of the Form"],
  ["Rito della Soglia","Ritual of the Threshold"],
  ["Rito di commemorazione dei defunti","Ritual of the Commemoration of the Dead"],
  ["Rito di comunione con il luogo","Ritual of Communion with the Land"],
  ["Rito di raccolta delle erbe","Ritual of the gathering of herbs"],
  ["Rituale","Ritual"],
  ["Sacralizzare","To hallow"],
  ["Sacrificio (delle erbe, per esempio)","Offering"],
  ["Sala dei Metalli","Hall of Metals"],
  ["Sala dell'Acqua","Hall of Water"],
  ["Sala del Tempo dei Popoli","Hall of the Time of Peoples"],
  ["Sala della Terra","Hall of the Earth"],
  ["Sala della Vittoria","Hall of Victory"],
  ["Sala delle Sfere","Hall of Spheres"],
  ["Sala preghiera","Prayer Room"],
  ["Scuola d'Arte","Damanhurian School of the Arts"],
  ["Scuola di Alchimia","Alchemy School"],
  ["Scuola di Guarigione Spirituale","School of Spiritual Healing"],
  ["Scuola di Meditazione","School of Meditation"],
  ["Scuola iniziatica","School of Initiation"],
  ["Mystery School","Mystery School"],
  ["Sdoppiamento","Out of Body experience"],
  ["Self","Selfic device"],
  ["Selfica","Selfica"],
  ["Sensi Interni","Inner Senses"],
  ["Senso del Desiderio","Sense of Desire"],
  ["Senso del Divino","Sense of Divine"],
  ["Senso del Sogno","Sense of Dreaming"],
  ["Senso della Memoria","Sense of Memory"],
  ["Senso dello Scambio","Sense of Exchange"],
  ["Serata","Serata","L'incontro damanhuriano che si tiene una volta a settimana.","The Damanhurian meeting held once a week."],
  ["Sferoself","Spheroself"],
  ["Signori del Consiglio","Lords of the Council"],
  ["Signori del karma","Lords of karma"],
  ["Signori del luogo","Guardians of the Land"],
  ["Sincronicità","Synchronicity"],
  ["Soglia (La)","The Threshold"],
  ["Specchio per divinazione","Scrying mirror"],
  ["Spirale dei Cristalli","Crystal Spiral"],
  ["Spirali","Spirals"],
  ["Spiriti di Natura","Nature spirits"],
  ["Stiloself","Stiloself"],
  ["Strutture selfiche","Selfic structures"],
  ["Superindividuo","Superindividual"],
  ["Tappi","Tappi","Persone che condividono la missione di Damanhur (dal racconto dei Tappi).","Individuals who share Damanhur's mission (from the Tale of the Corks)."],
  ["Tarocchi","Tarot cards"],
  ["Tecnarcato","Tecnarcato"],
  ["Teoretici","Group of Theoretical Studies"],
  ["Tempio Aperto","Open Temple"],
  ["Tempio Azzurro","Blue Temple"],
  ["Tempio della Concordanza","Temple of Concordance"],
  ["Tempio Preghiera","Prayer Temple"],
  ["Templi dell'Umanità","Temples of Humankind"],
  ["Temponauta","Time-naut (time traveler)"],
  ["Terrazzatura","Terrazzatura","Lavoro devozionale.","Devotional work."],
  ["Tessuto del tempo","Fabric of time"],
  ["Timoniere","Helmsperson"],
  ["Triade (La)","The Triad"],
  ["Tre fiumi","Three Rivers"],
  ["Università Indipendente di Damanhur","Independent University of Damanhur"],
  ["Vajne","Vajne","Il progetto universale di evoluzione dell'Umanità.","The universal project of evolution of Humanity."],
  ["Via Damanhur","Way of Damanhur"],
  ["Via dei Cavalieri","Way of the Knights"],
  ["Via dell'Arte","Way of the Arts"],
  ["Via dell'Oracolo","Way of the Oracle"],
  ["Via della Parola","Way of the Word"],
  ["Via della Salute e Olio Caldo","Way of Health and Olio Caldo"],
  ["Via delle Coppie Esoteriche","Way of Esoteric Couples"],
  ["Via Monacale","Way of the Monks"],
  ["Viaggio","Viaggio (Journey)","Il Viaggio inteso in senso damanhuriano.","The Journey in the Damanhurian sense."],
  ["Viaggio Astrale","Astral Travel"],
  ["Viaggio nel Tempo","Time travel"],
  ["Vite precedenti","Past Lives"],
  ["Vivere l'attimo","Living the moment"],
  ["Vortice temporale","Time vortex"],
];
export default GLOSSARY;
